export const BIT_TRADING_QUEUE = 'BIT_TRADING_QUEUE';
export const ADD_USER = 'ADD_USER';
export const ADD_REPORT = 'ADD_REPORT';
export const SYNC_PLAYER_DATA_TO_CACHE = 'SYNC_PLAYER_DATA_TO_CACHE';
